import RootLayout from '$layouts/RootLayout'

const LandingPage = () => {
  return (
    <RootLayout>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1>dfdfdf</h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
      <h1></h1>
    </RootLayout>
  )
}

export default LandingPage
